services:
  # --- DATABASE ---
  db:
    image: postgres:16-alpine
    container_name: GingillaFarm-postgres-db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${EXTERNAL_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # --- MICROSERVERS ---
  db_manager:
    build:
      context: ./buildings/microservers/db_manager
    container_name: db_manager
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db

  # --- LIMODIM ---
  limodim-backend:
    build:
      context: ./buildings/Limodim/server
    container_name: limodim_backend
    restart: always
    ports:
      - "${BACKEND_PORT}:8002"
    environment:
      - DB_MANAGER_URL=${DB_MANAGER_URL}
      - DB_NAME=${DB_NAME}
      - PDF_STORAGE_PATH=${INTERNAL_PDF_STORAGE_PATH}
    env_file: .env
    volumes:
      - ./buildings/Limodim/server:/app
      - ${HOST_PDF_STORAGE_PATH}:${INTERNAL_PDF_STORAGE_PATH}
    depends_on:
      - db
      - db_manager

  limodim-frontend:
    build:
      context: ./buildings/Limodim/client
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: limodim_frontend
    restart: always
    ports:
      - "${FRONTEND_PORT}:3100"
    depends_on:
      - limodim-backend

  # --- MAP VIEWER ---
  farm-map:
    image: nginx:stable-alpine
    container_name: gingilla_map
    ports:
      - "${MAP_PORT}:80"
    volumes:
      - ./Map:/usr/share/nginx/html:ro
    restart: always

  # --- ICON PROJECT ---
  icon-backend:
    build:
      context: ./buildings/Icons/server 
    container_name: icon_backend
    restart: always
    ports:
      - "${ICON_BACKEND_PORT_EXTERNAL}:8301"
    environment:
      - DB_MANAGER_URL=${DB_MANAGER_URL}
    depends_on:
      - db_manager

  icon-frontend:
    build:
      context: ./buildings/Icons/client
      args:
        VITE_ICONS_API_URL: ${VITE_ICONS_API_URL}
    container_name: icon_frontend
    restart: always
    ports:
      - "${ICON_FRONTEND_PORT_EXTERNAL}:8300"
    depends_on:
      - icon-backend

volumes:
  postgres_data: